version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: tpfoyer_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  app-tpfoyer:
    image: shadhanej/tp-foyer:0.2.1
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON: >-
        {
          "spring.datasource.url": "jdbc:mysql://mysqldb:3306/tpfoyer_db?createDatabaseIfNotExist=true",
          "spring.datasource.username": "root",
          "spring.datasource.password": "",
          "spring.jpa.show-sql": true,
          "spring.jpa.hibernate.ddl-auto": "update",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
          "server.port": 8082,
          "server.servlet.context-path": "/tpfoyer",
          "management.endpoints.web.exposure.include": "prometheus",
          "management.endpoint.prometheus.enabled": true
        }
    stdin_open: true
    tty: true

  app-front:
    image: shadhanej/angular
    ports:
      - "80:80"
    restart: on-failure
    depends_on:
      app-tpfoyer:
        condition: service_started  # Fix dependency on backend service (app-tpfoyer)


volumes:
  db:
