services:
  app:
    build: .
    image: my-new-app-image:latest
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/foyer?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_APPLICATION_JSON: >-
        {
          "spring": {
            "jpa": {
              "hibernate": {
                "ddl-auto": "update"
              },
              "show-sql": true
            },
            "datasource": {
              "url": "jdbc:mysql://db:3306/foyer?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
              "username": "root",
              "password": "root"
            }
          }
        }
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
