version: '3'
services:
  spring-app:
    image: imagedockerfile:latest  # L'image Docker que vous allez construire
    container_name: spring-container
    build: .
    ports:
      - "8080:8080"  # Le port 8080 de l'hôte mappe le port 8080 du conteneur
    depends_on:
      - mysql  # Assurez-vous que MySQL démarre avant Spring
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/foyer?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""  # Laisser vide si aucun mot de passe n'est utilisé
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SERVER_PORT: 8081
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true

  mysql:
    image: mysql:5.7  # Utilisation de l'image officielle MySQL 5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ""  # Si vous n'avez pas de mot de passe, laissez vide
      MYSQL_DATABASE: foyer  # Créer la base de données foyer
    ports:
      - "3306:3306"  # Le port 3306 de l'hôte mappe le port 3306 du conteneur
    volumes:
      - mysql-data:/var/lib/mysql  # Persistance des données MySQL

volumes:
  mysql-data:  # Volume persistant pour stocker les données de la base MySQL
