version: '3.8'

services:
  app:
    image: my-app-image:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app.jar:/app/app.jar
    ports:
      - "8082:8082"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
