version: "3.9"
services:
  db-mysql:
    image: "mysql:5.6"
    container_name: db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=foyer
    ports:
      - "3306:3306"
    restart: unless-stopped

  app:
    container_name: tp-foyer
    build: .
    ports:
      - "8087:8087"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/foyer?createDatabaseIfNotExist=true&userSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    image: tp-foyer:1.0
    depends_on:
      - db-mysql
