version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/foyer
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""  # Laisser vide si aucun mot de passe n'est utilisé
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ""  # Laisser vide si aucun mot de passe n'est utilisé
      MYSQL_DATABASE: foyer
      MYSQL_USER: root
      MYSQL_PASSWORD: ""  # Laisser vide si aucun mot de passe n'est utilisé
    ports:
      - "3306:3306"
